### ISSUE TITLE
Create better IDs for S3 Records

### ISSUE THREAD

**Issue by bjinwright** [kevproject/kev#12]
Check out the following article and YouTube video to learn why this is important for performance.
http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html#introduce-randomness-hash and https://youtu.be/x3wxVCvqpa8?t=47m29s

**Comment by mcrowson** [comment]
So it looks like the hash is really important for hardware distribution. At the end of the Q&A the guy says you need a secondary index if you want to use hash keys (which makes sense). Rather than use a DynamoDB as the secondary index, could a single document, or small set of documents, in S3 (maybe behind cloudfront) serve the same purpose with less cost? Further it keeps it pure S3 which I like for simplicity sake.

**Comment by bjinwright** [comment]
Check out my answer here. https://github.com/kevproject/kev/issues/10#issuecomment-248345152

**Comment by bjinwright** [comment]
This is fixed in https://github.com/kevproject/kev/commit/493741a0c241ddff14939a15ed592051b218fa29
